### ISSUE TITLE
Unable to delete folders and only files via SSH to a Linux box. 

### ISSUE THREAD

**Issue by georgcmef** [SchoofsKelvin/vscode-sshfs#258]
When I select a folder that contains any files I am unable to delete the folder. When it is an empty folder I have no problem. Thank you. This is what I get in the output:

    [DEBUG]   Deleting ssh://mia_dev_george/zzz_globalDELETE/images

     [ERROR]   Error handling uri: ssh://mia_dev_george/zzz_globalDELETE/images

     [ERROR]   Failure

     JSON: {"code":4,"lang":""}

    Error: Failure
    at O._transform (c:\Users\xxxxxx\.vscode\extensions\kelvin.vscode-sshfs-1.20.1\dist\0.extension.js:1:76072)

    at O.Transform._read (_stream_transform.js:191:10)

    at O._read (c:\Users\xxxxxx\.vscode\extensions\kelvin.vscode-sshfs-1.20.1\dist\0.extension.js:1:72077)

     Logged at:

    at c:\Users\xxxxxx\.vscode\extensions\kelvin.vscode-sshfs-1.20.1\dist\4.extension.js:1:3583

**Comment by SchoofsKelvin** [comment]
Seems like VS Code didn't specify `recursive` or the path somehow isn't recognized as a directory, since line 173 errored:
https://github.com/SchoofsKelvin/vscode-sshfs/blob/6cd441ab412912bbfc3d3202fd3c33b60033f15b/src/sshFileSystem.ts#L162-L176

A few questions:
- To delete, I assume you use right-click in the explorer or select it in the explorer and press your delete key?
- Is the folder you're trying to delete a regular directory? E.g. not a symbolic link? or having unusual permissions?

**Comment by georgcmef** [comment]
Yeah I right clicks and selective delete from the drop-down menu. And it is a regular folder with 777 permissions so nothing fancy.
