### ISSUE TITLE
no matching host key format

### ISSUE THREAD

**Issue by jjcarstens** [SchoofsKelvin/vscode-sshfs#291]
My server is using host key format `rsa-sha2-256`. However, that is not working with ssh2 it seems

<details>
<summary>no matching host key format log</summary>

```
[INFO]    [createSocket(nerves_livebook)] Creating socket
[DEBUG]   [createSocket(nerves_livebook)] Connecting to nerves.local:22
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Local ident: 'SSH-2.0-ssh2js0.4.10'
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Parser: IN_INIT
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Parser: IN_GREETING
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Parser: IN_HEADER
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Remote ident: 'SSH-2.0-wdnta'
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Outgoing: Writing KEXINIT
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Parser: IN_PACKET
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Parser: pktLen:676,padLen:11,remainLen:672
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Parser: IN_PACKETDATA
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXINIT
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Comparing KEXINITs ...
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: (local) KEX algorithms: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha1
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: (remote) KEX algorithms: diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ext-info-s
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: KEX algorithm: curve25519-sha256@libssh.org
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: (local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: (remote) Host key formats: rsa-sha2-256,rsa-sha2-512
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: No matching host key format
[ERROR]   [createSSH(nerves_livebook)] Handshake failed: no matching host key format
Logged at:
    at T.<anonymous> (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:224709)
    at T.emit (events.js:315:20)
    at fe.<anonymous> (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:251233)
    at fe.emit (events.js:327:22)
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:116689
Reported from createSSH(nerves_livebook)
[DEBUG]   [ssh2(nerves_livebook)] DEBUG: Outgoing: Writing DISCONNECT (KEY_EXCHANGE_FAILED)
[ERROR]   Error while connecting to SSH FS nerves_livebook:
Handshake failed: no matching host key format
Logged at:
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:880760
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR]   Handshake failed: no matching host key format
JSON: {"level":"handshake","vslsStack":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}
Error: Handshake failed: no matching host key format
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:116609
    at o (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:120394)
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:120716
    at fe.<anonymous> (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:120720)
    at fe.emit (events.js:315:20)
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:138314
    at le (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:138334)
    at fe._transform (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:154536)
    at fe.Transform._read (internal/streams/transform.js:205:10)
    at fe._read (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:148424)
Caused by promise:
    at C.createFileSystem (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:879106)
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:881009
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Logged at:
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:880827
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
</details>

If I add the host key format to the `serverHostKey` setting, it says `Unsupported server host key algorithm: rsa-sha2-256`

<details>
<summary> full log </summary>

```
INFO]    [createConnection(nerves_livebook,config)] Creating a new connection for 'nerves_livebook'
[INFO]    Calculating actual config
[DEBUG]   	Final configuration:
{
    "name": "nerves_livebook",
    "host": "nerves.local",
    "username": "livebook",
    "password": "<censored>",
    "root": "/data",
    "algorithms": {
        "serverHostKey": [
            "rsa-sha2-256",
            "ssh-rsa",
            "ecdsa-sha2-nistp256",
            "ecdsa-sha2-nistp384",
            "ecdsa-sha2-nistp521"
        ]
    },
    "agentForward": false,
    "_location": 1,
    "_locations": [
        1
    ],
    "_calculated": {
        "name": "nerves_livebook",
        "host": "nerves.local",
        "username": "livebook",
        "password": "<censored>",
        "root": "/data",
        "agent": "$SSH_AUTH_SOCK",
        "algorithms": {
            "serverHostKey": [
                "rsa-sha2-256",
                "ssh-rsa",
                "ecdsa-sha2-nistp256",
                "ecdsa-sha2-nistp384",
                "ecdsa-sha2-nistp521"
            ]
        },
        "agentForward": false,
        "_location": 1,
        "_locations": [
            1
        ]
    },
    "port": 22
}
[INFO]    [createSocket(nerves_livebook)] Creating socket
[DEBUG]   [createSocket(nerves_livebook)] Connecting to nerves.local:22
[ERROR]   Error while connecting to SSH FS nerves_livebook:
Unsupported server host key algorithm: rsa-sha2-256
Logged at:
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:880760
[ERROR]   Unsupported server host key algorithm: rsa-sha2-256
JSON: {"vslsStack":[{},{},{},{},{}]}
Error: Unsupported server host key algorithm: rsa-sha2-256
    at T.connect (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:247421)
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:225196
    at new Promise (<anonymous>)
    at v (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/589.extension.js:1:224189)
    at t._createConnection (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:875500)
Caused by promise:
    at C.createFileSystem (/Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:879106)
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:881009
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Logged at:
    at /Users/jonjon/.vscode/extensions/kelvin.vscode-sshfs-1.22.0/dist/extension.js:1:880827
```
</details>

However, that seems to be a [valid option in the latest ssh2](https://www.npmjs.com/package/ssh2/v/1.4.0#client-methods). Is this extension using an outdated version of `ssh2` maybe? (I dont really know how this all works with js and vscode)

**Comment by SchoofsKelvin** [comment]
I took a look at it, and it seems `rsa-sha2-256` and `rsa-sha2-512` got added in ssh2's big rewrite (v1.0.0). The extension is written for and still using (a slightly altered version of) v0.8.9, as there were some big (API-breaking) changes. _Most importantly, the package (currently) doesn't expose certain classes anymore that the extension needs._

I'll look into still upgrading ssh2 and using the (now) unofficially exported features, or modify it to export it anyway.
