### ISSUE TITLE
Quick open not working

### ISSUE THREAD

**Issue by NightProgramming** [SchoofsKelvin/vscode-sshfs#316]
Pressing Ctr + P and entering a path e.g. `/etc/nginx/nginx.conf ` results in the following error:

```
[ERROR]   Error while connecting to SSH FS :
Error: Couldn't find a configuration with the name ''
Error: Couldn't find a configuration with the name ''
	at c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:20097
	at Promise.catch.r (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:6471)
	at new Promise (<anonymous>)
	at i (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:6027)
	at m.createFileSystem (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:20051)
	at o.assertFs (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:9989)
	at o.stat (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:10096)
	at u.$stat (c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:80391)
	at t._doInvokeHandler (c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13802)
	at t._invokeHandler (c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13486)
Caused by catchingPromise:
	at i (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:6027)
	at m.createFileSystem (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:20051)
	at o.assertFs (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:9989)
	at o.stat (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:10096)
	at u.$stat (c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:80391)
	at t._doInvokeHandler (c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13802)
	at t._invokeHandler (c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13486)
	at t._receiveRequest (c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12148)
	at t._receiveOneMessage (c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:10826)
	at c:\Users\MyUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:8922
Logged at:
	at c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:21714
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async o.stat (c:\Users\MyUser\.vscode\extensions\kelvin.vscode-sshfs-1.24.1\dist\extension.js:11:10085)
```

Using Windows 10 and on remote Ubuntu 20.04.3 LTS with OpenSSH_8.2p1 Ubuntu-4ubuntu0.3, OpenSSL 1.1.1f .

**Comment by SchoofsKelvin** [comment]
Hmm it looks like looking for `/path` while you have `ssh://config/directory/` open makes VS Code actually look in `ssh:///directory/path`, with an empty authority (it should start with `ssh://config/`). I'll see if I can just have it default to the first `ssh://` workspace folder available.

Weirdly enough, using the Open File prompt (`Ctrl+o`) works just fine.
