### ISSUE TITLE
Unable to start subsystem: sftp

### ISSUE THREAD

**Issue by Xigma101** [SchoofsKelvin/vscode-sshfs#384]
The current issue is affecting both me and around 5 others within my workplace, on multiple different computers, both windows and macOs, along with different servers although they would all be linux based.

When we try to connect to an existing server with a config, that was previously working and has had no changes too, an error pops up on the right hand saying the following:

"Error while connecting to SSH FS <hostname>: Unable to start subsystem sftp"

So after reading into this I've found that you can add debug flags into the config like so:

`
    "sshfs.flags": [
        "DEBUG_SSH2"
    ]
`

This has produced the following log ( I have cleaned out any sensitive related to the server or myself ):

"
[INFO]    [getSFTP(<hostname>)] Creating SFTP session using standard sftp subsystem
[DEBUG]   [ssh2(<hostname>)] Outbound: Sending CHANNEL_OPEN (r:2, session)
[DEBUG]   [ssh2(<hostname>)] Inbound: CHANNEL_OPEN_CONFIRMATION (r:2, s:0)
[DEBUG]   [ssh2(<hostname>)] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[DEBUG]   [ssh2(<hostname>)] Inbound: CHANNEL_FAILURE (r:2)
[ERROR]   Error while connecting to SSH FS <hostname>:
Error: Unable to start subsystem: sftp
Error: Unable to start subsystem: sftp
	at c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:83725
	at CHANNEL_FAILURE (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:95289)
	at 100 (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:251024)
	at e.exports.D (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:111513)
	at D.decrypt (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:205168)
	at e.exports.H [as _parse] (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:111037)
	at e.exports.parse (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:114840)
	at Socket.<anonymous> (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:96586)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
Caused by toPromise:
	at y (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\14f8.extension.js:1:63717)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\extension.js:1:64947
Caused by catchingPromise:
	at i (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\extension.js:11:6399)
	at E.createFileSystem (c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\extension.js:1:64587)
Logged at:
	at c:\Users\<username>\.vscode\extensions\kelvin.vscode-sshfs-1.26.1\dist\extension.js:1:66250
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[DEBUG]   [ssh2(<hostname>)] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[DEBUG]   [ssh2(<hostname>)] Inbound: Received REQUEST_FAILURE
[DEBUG]   [ssh2(<hostname>)] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[DEBUG]   [ssh2(<hostname>)] Inbound: Received REQUEST_FAILURE
"

Yesterday there was an issue with the original SSH RSA SHA-1 key that we using, but after updating the SSH keys to SSH ed25519 it temporarily resolved the issue, but today now this new issue saying "Unable to start subsystem: sftp" and I have no idea how to proceed from here.

**Comment by Xigma101** [comment]
This ended up being an issue with the server, after reseting the server and the SFTP and SSH service all worked as intended.
