### ISSUE TITLE
All configured authentication methods failed in 1.26.1 but not in 1.26.0

### ISSUE THREAD

**Issue by Xigma101** [SchoofsKelvin/vscode-sshfs#385]
The current issue being presented is only happening in version 1.26.1 for a collegue of mine, I am also using the same version and connecting to the same server with the same SSH encryption, ed25519, and currently experiencing no issues.

I've set the debug flag to "DEBUG_SSH2" in SSH FS and grabbed this log from when they tried to connect to the server.

`
[INFO]    Version history: 1.26.0:1681892628828:1681892628828 > 1.26.1:1681892628828:1681917376342

[INFO]    [createConnection(<host>,config)] Creating a new connection for '<host>'

[INFO]    Calculating actual config

[DEBUG]     Read private key from /Users/<user>/.ssh/id_ed25519

[DEBUG]     Final configuration:

{

    "name": "<host>",

    "privateKeyPath": "/Users/<user>/.ssh/id_ed25519",

    "passphrase": "<censored>",

    "host": "85.92.73.67",

    "username": "<host>",

    "password": "<censored>",

    "_location": 1,

    "_locations": [

        1

    ],

    "_calculated": {

        "name": "<host>",

        "privateKeyPath": "/Users/<user>/.ssh/id_ed25519",

        "passphrase": "<censored>",

        "host": "<ip>",

        "username": "<host>",

        "password": "<censored>",

        "_location": 1,

        "_locations": [

            1

        ]

    },

    "port": 22,

    "privateKey": "Buffer(484)"

}

[INFO]    [createSocket(<host>)] Creating socket

[DEBUG]   [createSocket(<host>)] Connecting to <ip>

[INFO]    [createSSH(<host>)] Flag "OPENSSH-SHA1" enabled due to 'missing', including convertSha1 for publickey authentication

[INFO]    [createSSH(<host>)] Flag "OPENSSH-SHA1" enabled due to 'missing'

[DEBUG]   [ssh2(<host>)] Custom crypto binding not available

[DEBUG]   [ssh2(<host>)] Local ident: 'SSH-2.0-ssh2js1.11.0'

[DEBUG]   [ssh2(<host>)] Socket connected

[DEBUG]   [ssh2(<host>)] Remote ident: 'SSH-2.0-OpenSSH_7.4'

[DEBUG]   [ssh2(<host>)] Outbound: Sending KEXINIT

[DEBUG]   [ssh2(<host>)] Inbound: Handshake in progress

[DEBUG]   [ssh2(<host>)] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512

[DEBUG]   [ssh2(<host>)] Handshake: (remote) KEX method: diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,curve25519-sha256,curve25519-sha256@libssh.org,gss-gex-sha1-,gss-group14-sha1-

[DEBUG]   [ssh2(<host>)] Handshake: KEX algorithm: curve25519-sha256@libssh.org

[DEBUG]   [ssh2(<host>)] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa

[DEBUG]   [ssh2(<host>)] Handshake: (remote) Host key format: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519

[DEBUG]   [ssh2(<host>)] Handshake: Host key format: ssh-ed25519

[DEBUG]   [ssh2(<host>)] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr

[DEBUG]   [ssh2(<host>)] Handshake: (remote) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com

[DEBUG]   [ssh2(<host>)] Handshake: C->S Cipher: aes128-gcm@openssh.com

[DEBUG]   [ssh2(<host>)] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr

[DEBUG]   [ssh2(<host>)] Handshake: (remote) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com

[DEBUG]   [ssh2(<host>)] Handshake: S->C cipher: aes128-gcm@openssh.com

[DEBUG]   [ssh2(<host>)] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1

[DEBUG]   [ssh2(<host>)] Handshake: (remote) C->S MAC: hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,umac-128@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com

[DEBUG]   [ssh2(<host>)] Handshake: C->S MAC: <implicit>

[DEBUG]   [ssh2(<host>)] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1

[DEBUG]   [ssh2(<host>)] Handshake: (remote) S->C MAC: hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,umac-128@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com

[DEBUG]   [ssh2(<host>)] Handshake: S->C MAC: <implicit>

[DEBUG]   [ssh2(<host>)] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib

[DEBUG]   [ssh2(<host>)] Handshake: (remote) C->S compression: none,zlib@openssh.com

[DEBUG]   [ssh2(<host>)] Handshake: C->S compression: none

[DEBUG]   [ssh2(<host>)] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib

[DEBUG]   [ssh2(<host>)] Handshake: (remote) S->C compression: none,zlib@openssh.com

[DEBUG]   [ssh2(<host>)] Handshake: S->C compression: none

[DEBUG]   [ssh2(<host>)] Outbound: Sending KEXECDH_INIT

[DEBUG]   [ssh2(<host>)] Received DH Reply

[DEBUG]   [ssh2(<host>)] Host accepted by default (no verification)

[DEBUG]   [ssh2(<host>)] Host accepted (verified)

[DEBUG]   [ssh2(<host>)] Outbound: Sending NEWKEYS

[DEBUG]   [ssh2(<host>)] Inbound: NEWKEYS

[DEBUG]   [ssh2(<host>)] Verifying signature ...

[DEBUG]   [ssh2(<host>)] Verified signature

[DEBUG]   [ssh2(<host>)] Handshake completed

[DEBUG]   [ssh2(<host>)] Outbound: Sending SERVICE_REQUEST (ssh-userauth)

[DEBUG]   [ssh2(<host>)] Inbound: Received SERVICE_ACCEPT (ssh-userauth)

[DEBUG]   [ssh2(<host>)] Outbound: Sending USERAUTH_REQUEST (none)

[DEBUG]   [ssh2(<host>)] Inbound: Received USERAUTH_FAILURE (publickey,gssapi-keyex,gssapi-with-mic)

[DEBUG]   [ssh2(<host>)] Client: none auth failed

[DEBUG]   [ssh2(<host>)] Outbound: Sending USERAUTH_REQUEST (password)

[DEBUG]   [ssh2(<host>)] Inbound: Received USERAUTH_FAILURE (publickey,gssapi-keyex,gssapi-with-mic)

[DEBUG]   [ssh2(<host>)] Client: password auth failed

[DEBUG]   [ssh2(<host>)] Skipping invalid key auth attempt

[DEBUG]   [ssh2(<host>)] Outbound: Sending USERAUTH_REQUEST (keyboard-interactive)

[DEBUG]   [ssh2(<host>)] Inbound: Received USERAUTH_FAILURE (publickey,gssapi-keyex,gssapi-with-mic)

[DEBUG]   [ssh2(<host>)] Client: keyboard-interactive auth failed

[ERROR]   [createSSH(<host>)] Error: All configured authentication methods failed

JSON: {"level":"client-authentication"}

Error: All configured authentication methods failed

  at _e (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:97846)

  at Ie (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:100799)

  at USERAUTH_FAILURE (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:89153)

  at 51 (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:241614)

  at e.exports.D (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:111513)

  at D.decrypt (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:205168)

  at e.exports.H [as _parse] (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:111037)

  at e.exports.parse (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:114840)

  at Socket.<anonymous> (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:96586)

  at Socket.emit (node:events:526:28)

Logged at:

  at e.exports.emit (node:events:526:28)

  at _e (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:97948)

  at Ie (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:100799)

  at USERAUTH_FAILURE (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:89153)

  at 51 (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:241614)

Reported by logger createSSH(<host>)

[DEBUG]   [ssh2(<host>)] Outbound: Sending DISCONNECT (11)

[ERROR]   Error while connecting to SSH FS <host>:

Error: All configured authentication methods failed

JSON: {"level":"client-authentication"}

Error: All configured authentication methods failed
  at _e (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:97846)

  at Ie (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:100799)

  at USERAUTH_FAILURE (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:89153)

  at 51 (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:241614)

  at e.exports.D (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:111513)

  at D.decrypt (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:205168)

  at e.exports.H [as _parse] (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:111037)

  at e.exports.parse (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:114840)

  at Socket.<anonymous> (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:96586)

  at Socket.emit (node:events:526:28)

Caused by catchingPromise:

  at i (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:11:6399)

  at E.createFileSystem (/Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:1:64587)

  at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

Logged at:

  at /Users/<user>/.vscode/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:1:66250

  at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

[DEBUG]   [ssh2(<host>)] Socket ended

[DEBUG]   [ssh2(<host>)] Socket closed
`

Immediately after having this fail, we decided to test the previous version which is 1.26.0 and this worked without fail.

**Comment by Wasca** [comment]
I'm experiencing the same issue. I rolled back to 1.26.0 and it works again.

**Comment by anselal** [comment]
Same here. Rolled back to 1.26.0 and it works

**Comment by jazzroutine** [comment]
Same here

**Comment by alteiis** [comment]
Same here. 1.26.0 rollback and all is fine.

**Comment by syther05** [comment]
I can confirm same issue here also.
1.26.0 rollback fixed it

**Comment by MRVDH** [comment]
Same

**Comment by wuhelong** [comment]
Same

**Comment by geesewild** [comment]
Had the same issue with 1.26.1 when using ed25519. It works fine with rsa. 

I eventually added "-OPENSSH-SHA1" to sshfs.flags and it worked.

**Comment by Wasca** [comment]
I can confirm that adding this value to the settings.json file worked.

``` JSON
"sshfs.flags": [
    "-OPENSSH-SHA1"
  ]
```

**Comment by ZeroCommits** [comment]
> I can confirm that adding this value to the settings.json file worked.
> 
> ```json
> "sshfs.flags": [
>     "-OPENSSH-SHA1"
>   ]
> ```

Thanks @Wasca this fixed it for me.
