### ISSUE TITLE
No support for ed25519-sk ssh keys

### ISSUE THREAD

**Issue by timhorn1** [SchoofsKelvin/vscode-sshfs#416]
```
[INFO]    [createSocket(tr3_config)] Creating socket
[DEBUG]   [createSocket(tr3_config)] Connecting to 192.168.178.70:22
[INFO]    [createSSH(tr3_config)] Flag "OPENSSH-SHA1" enabled due to 'missing', including convertSha1 for publickey authentication
[INFO]    [createSSH(tr3_config)] Flag "OPENSSH-SHA1" enabled due to 'missing'
[ERROR]   Error while connecting to SSH FS tr3_config:
Error: Cannot parse privateKey: **Unsupported OpenSSH private key type: sk-ssh-ed25519@openssh.com**
Error: Cannot parse privateKey: Unsupported OpenSSH private key type: sk-ssh-ed25519@openssh.com
	at e.exports.connect (/home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:87603)
	at /home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:63301
	at new Promise (<anonymous>)
	at I (/home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/14f8.extension.js:1:61446)
	at async g._createConnection (/home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:1:59429)
Caused by catchingPromise:
	at /home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:11:6594
	at Promise.catch.o (/home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:11:6684)
	at new Promise (<anonymous>)
	at i (/home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:11:6399)
	at E.createFileSystem (/home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:1:64587)
Logged at:
	at /home/timh/.vscode-oss/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:1:66250
```

**Comment by Fischmuetze** [comment]
same here - sad - therefore currently unusable

**Comment by SchoofsKelvin** [comment]
This might be the same issue as (or cause of) #435. I don't have a physical security key nor does the extension's underlying `ssh2` library seem to support it (mscdex/ssh2#1206) so it'll be tricky. I'll take a look at whether I can test it myself and work around the issue.

**Comment by SchoofsKelvin** [comment]
Looked a bit into patching it into `ssh2` myself, two main points regarding that:

- Having the extension directly use `sk-*` private keys is basically impossible, as it needs to interact with the OS in some way to actually use the private key (i.e. Windows Hello, talk with a Yubi key, ...). I highly doubt that'll be added anytime soon, if at all. I don't see an easy way to do this either, let alone get it working cross-platform and publishable with the extension.
- I succeeded in getting it mostly working with the OpenSSH agent on Windows (i.e. `ssh-add`) which therefore _should_ work on Mac/Linux too. I say mostly, as I succeeded in getting and parsing the public `sk-*` from the agent, exchanging it with the remote server, signing using the private key locally (through the agent), but my test server complains the signature is in the wrong format, so something's still wrong. Might look more into it, unlikely to be done (properly) soon, but there's at least a good possibility.

**Comment by jogemu** [comment]
I commented a workaround on the ssh2 issue you linked to. You should be able to test it without a physical key using `ssh-keygen -t ecdsa-sk`, provided your TPM or phone supports it. Before I patch this (or you if you are still interested) I'd appreciate a second opinion whether the approach makes sense.

**Comment by moppi79** [comment]
I have the same problem 
our Company uses ed25519 ... global. 

i use your plugin very often at home i love it. 

i hope you find a solution to this problem. want a window IDE ... not forced to use VIM
