### ISSUE TITLE
SSH-FS Connection failing: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by CentillionJinx** [SchoofsKelvin/vscode-sshfs#430]
I am trying to login to my school server to do some homework, but I can't seem to access it anymore. I have not done anything different since the last time it was able to access it, hence begs the question, what has changed?

`Output - SSH-FS`

```
[INFO]    Command received to open a terminal for FileSystemConfig(cse@unsw)
[INFO]    [createConnection(cse@unsw,config)] Creating a new connection for 'cse@unsw'
[INFO]    Calculating actual config
[DEBUG]   	Final configuration:
{
    "name": "cse@unsw",
    "host": "login9.cse.unsw.edu.au",
    "username": "School ID",
    "password": "<censored>",
    "newFileMode": "0o777",
    "root": "/home/user/Documents",
    "_location": 1,
    "_locations": [
        1
    ],
    "_calculated": {
        "name": "cse@unsw",
        "host": "login9.cse.unsw.edu.au",
        "username": "School ID",
        "password": "<censored>",
        "newFileMode": "0o777",
        "root": "/home/user/Documents",
        "_location": 1,
        "_locations": [
            1
        ]
    },
    "port": 22
}
[INFO]    [createSocket(cse@unsw)] Creating socket
[DEBUG]   [createSocket(cse@unsw)] Connecting to login9.cse.unsw.edu.au:22
[ERROR]   Error while creating terminal:
Error: connect EHOSTUNREACH 129.94.242.159:22
JSON: {"errno":-113,"code":"EHOSTUNREACH","syscall":"connect","address":"129.94.242.159","port":22}
Error: connect EHOSTUNREACH 129.94.242.159:22
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
Logged at:
    at E.commandTerminal (/home/hexy/.vscode-insiders/extensions/kelvin.vscode-sshfs-1.26.1/dist/extension.js:1:70751)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at aw.h (file:///usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)

```

Any help would be great, I still need to start studying dsa... :/

edit: 
I was able to access the server through tigerVNC, so I am pretty sure that the server is up. My other friend using SSH-FS is also able to access the server through the extension, so is something wrong with my vscode? What else can I provide to resolve this issue, I jus want this to be resolved..

**Comment by CentillionJinx** [comment]
nvm resolved. I updated vscode, and changed the connection URL.
